insert into author (slug, name) values ('slug', 'Carlie Durno');
insert into author (slug, name) values ('slug', 'Benedict Ricoald');
insert into author (slug, name) values ('slug', 'Martha Balmann');
insert into author (slug, name) values ('slug', 'Alfredo Moggle');
insert into author (slug, name) values ('slug', 'Thorin Casero');
insert into author (slug, name) values ('slug', 'Anson Aimer');
insert into author (slug, name) values ('slug', 'Marge Tennock');
insert into author (slug, name) values ('slug', 'Donnell Marrian');
insert into author (slug, name) values ('slug', 'Chase Hyslop');
insert into author (slug, name) values ('slug', 'Bertine Fanti');
insert into author (slug, name) values ('slug', 'Nataline De Carlo');
insert into author (slug, name) values ('slug', 'Riobard Nottingam');
insert into author (slug, name) values ('slug', 'Natassia Tessington');
insert into author (slug, name) values ('slug', 'Adham Castano');
insert into author (slug, name) values ('slug', 'Rosie Piscopiello');
insert into author (slug, name) values ('slug', 'Glynis Cortes');
insert into author (slug, name) values ('slug', 'Zachary Stocky');
insert into author (slug, name) values ('slug', 'Sheelah Treen');
insert into author (slug, name) values ('slug', 'Alessandra Roggerone');
insert into author (slug, name) values ('slug', 'Dotti Cartner');
insert into author (slug, name) values ('slug', 'Norene Church');

insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('19-06-2023', 1, 'slug', 'Fortune, The', 1142, 74);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('12-08-2023', 1, 'slug', 'The Feathered Serpent', 918, 30);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('21-05-2023', 0, 'slug', 'Killer Joe', 3986, 95);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('16-09-2023', 0, 'slug', 'Sweet Charity', 4875, 68);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('15-02-2023', 0, 'slug', 'Philadelphia Experiment, The', 3019, 27);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('29-01-2023', 0, 'slug', 'Count Dracula (Nachts, wenn Dracula erwacht)', 3065, 46);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('03-04-2023', 1, 'slug', 'Mediterraneo', 3532, 70);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('03-11-2023', 0, 'slug', 'Slumber Party ''57', 4065, 61);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('18-04-2023', 0, 'slug', 'Shadows Over Chinatown', 1863, 86);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('26-09-2023', 0, 'slug', 'Black Magic Rites & the Secret Orgies of the 14th Century (Riti, magie nere e segrete orge nel trecento...)', 4488, 17);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('04-03-2023', 1, 'slug', 'Canon', 3645, 60);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('18-05-2023', 1, 'slug', 'Make Your Move', 4619, 54);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('28-12-2022', 1, 'slug', 'Burn After Reading', 2232, 81);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('21-01-2023', 1, 'slug', 'Unfaithfully Yours', 3828, 40);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('20-05-2023', 0, 'slug', 'Film About a Woman Who...', 2017, 25);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('14-12-2023', 0, 'slug', 'Dancing in September', 3336, 43);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('29-06-2023', 0, 'slug', 'Nine Dead Gay Guys', 3875, 52);
insert into book (pub_date, is_bestseller, slug, title, price, discount) values ('03-12-2023', 1, 'slug', 'The Joy of Living', 1469, 32);

insert into book_file (type_id, path, hash) values (8, 'Sit.xls', '$2a$04$tGoC0PuqDF9HYKrRJ/9aTeKqvJk3gdPw/FRnYlJcCmDDP.G/DXkxe');
insert into book_file (type_id, path, hash) values (8, 'TinciduntInLeo.mp3', '$2a$04$AsnoxvE1vmZhCRgeJr.mlOl92x101aUHuNKAoAQQ4izwEQgv/qbqK');
insert into book_file (type_id, path, hash) values (8, 'Felis.mp3', '$2a$04$Z4PLfubopvM5QdSKpaAJN.OFuzpgrFePC27QHRLbZ8JFH2C2mn9Z.');
insert into book_file (type_id, path, hash) values (2, 'DapibusDuisAt.avi', '$2a$04$rB0SnX.PGbH25dvdtTAM6uBkp6uhOwvrcp.TFNjAAf/1ysJniVsFO');
insert into book_file (type_id, path, hash) values (7, 'Duis.mp3', '$2a$04$2mBYWpN/i.lE3yAfXHWlHezd1JE3uYBKdfvXJf0FaDHCpeWGDbdjG');
insert into book_file (type_id, path, hash) values (6, 'ConvallisTortorRisus.jpeg', '$2a$04$EyV0fvnfGbdQdaDsyru/xOvr0Cs0jdFnRzg77Qof8MgDFMKLpQsZ6');
insert into book_file (type_id, path, hash) values (9, 'DonecPharetra.tiff', '$2a$04$UM8xT3gRs9aMnMPiS5hx5ejX7w40PgNIZW9q0vXIPWXliyE6cwwwS');
insert into book_file (type_id, path, hash) values (8, 'VelIpsumPraesent.jpeg', '$2a$04$dgYlpPaJIw6Ona4PTVY7Qu5BMyvu1xBfJklpK9szdk6CBhzIpVMAa');
insert into book_file (type_id, path, hash) values (7, 'CongueEgetSemper.mp3', '$2a$04$ZGVXVs2Ov1cEt7MNB1nd/.9OqmRUwtHuiadNl1.I74cMhaL8LEQJi');
insert into book_file (type_id, path, hash) values (5, 'Etiam.ppt', '$2a$04$YDzcb9e.YLtMxpe3WhpPZOpsFPzMZ6v7zeUL1z//.XKix0Az6.AwS');
insert into book_file (type_id, path, hash) values (1, 'ProinEu.ppt', '$2a$04$2KuMzD8Xda5b9x74NpSF2eDRzpVb6KTgkRPCLd8YTTL9ZTOPzeKQ2');
insert into book_file (type_id, path, hash) values (4, 'Pede.ppt', '$2a$04$UwOhxvElNooeonTARldVZuMGj3o0ejhMgd/aEfVrQYYDdX3Yzo7ba');
insert into book_file (type_id, path, hash) values (1, 'Vestibulum.avi', '$2a$04$.F9g5LzvspN6nXCF7CvxwO3toLvUlso.dfkdGON2PyFGnfsy7aEBW');
insert into book_file (type_id, path, hash) values (4, 'NullamMolestieNibh.avi', '$2a$04$o0.dJbSv0Gra7ZbaHEYznuAWjlSM6TEG2sUMA1FNapbL/RlEZzLMq');
insert into book_file (type_id, path, hash) values (8, 'DuisBibendumFelis.xls', '$2a$04$Pe5n.p7ky3VWiOjQU3qtBuza2OyM6TamVPeEeFFSPAo1d41D5HcTi');
insert into book_file (type_id, path, hash) values (0, 'Ipsum.tiff', '$2a$04$oQdn1dJOP3v9zlR1pMu9Huy0ftE8PRTQbTymcRa1I.MdHvw/VLaoC');
insert into book_file (type_id, path, hash) values (1, 'DonecOdioJusto.avi', '$2a$04$u9XcyAIP3WgzGVTHezyb1ujKlHqSH0kfZ0Uemv6w79l9q0sqR9x3a');
insert into book_file (type_id, path, hash) values (3, 'NamCongue.png', '$2a$04$qivSc4frQUdVWczXSwgv/.PxbqqDkre43jji31JheHqncnRwUjSV.');
insert into book_file (type_id, path, hash) values (6, 'SapienNon.avi', '$2a$04$BPl4xC0N5zsSKBru6bx3T.vcxPFbeZksO58cORmQrr4WzOVjX8x6O');
insert into book_file (type_id, path, hash) values (3, 'Pellentesque.avi', '$2a$04$DmrYp1Uq9lLb3V2QHnLrRuPrfbXmi6vOnPnhoaH7xcdINw9xfKZUC');
insert into book_file (type_id, path, hash) values (0, 'Odio.ppt', '$2a$04$RdejaOjpRIIkZOjHOEH69.J5KwRxgG957UTWkrVCuKhKc2X3qXKLS');